#!/bin/bash
# Script to report Status information to a file on an inserted flash drive.

# continue if errors
set +e

# Full path of the script
script_path="$(readlink -f "$0")"
# Directory of the script
script_dir="$(dirname "$script_path")"

# get the Ethernet mac address of this computer to use in a file name.
# remove colons
mac=$(ip addr | grep link/ether | head -n1 | sed 's/^[[:space:]]*//' | cut -d ' ' -f2 | sed 's/://g')

# now make a file name with the mac and date/time
filename=/mnt/usb-sda1/$mac-$(date +%Y-%m-%d-%H%M%S).txt

echo -e "free -m:\n" >> $filename
free -m >> $filename

echo -e "\n______________\ndf:\n" >> $filename
df >> $filename

echo -e "\n______________\nuptime:\n" >> $filename
uptime >> $filename

echo -e "\n______________\nCPU Temperature: $((`cat /sys/class/thermal/thermal_zone0/temp`/1000)) deg C" >> $filename

echo -e "\n______________\nps aux | grep resol:\n" >> $filename
ps aux | grep resol >> $filename

echo -e "\n______________\nresol-to-lora last commit:\n" >> $filename
/usr/bin/git --git-dir=$script_dir/.git log -1  >> $filename

echo -e "\n______________\nresol-to-lora settings.py:\n" >> $filename
cat $script_dir/settings.py  >> $filename

echo -e "\n______________\nCurrent date/time & date/time of last resol live json file:\n" >> $filename
echo "Current: $(date)" >> $filename
echo "Resol live: $(ls -l $script_dir/../resol-vbus/examples/json-live-data-server/live-data.json)" >> $filename

echo -e "\n______________\nLog File for resol-to-lora script:\n" >> $filename
cat $script_dir/../log/resol-to-lora.log  >> $filename

echo -e "\n______________\nLive Resol Data file:\n" >> $filename
cat $script_dir/../resol-vbus/examples/json-live-data-server/live-data.json  >> $filename

umount /mnt/usb-sda1
